---
nome : Build - Windows - CMake
sobre :
  fluxo de trabalho_despacho :
  solicitação de pull :
    tipos : [aberto, sincronizado, reaberto, pronto_para_revisão]
    caminhos :
      - " origem/** "
  grupo de mesclagem :
  empurrar :
    caminhos :
      - " origem/** "
    galhos :
      - principal
ambiente :
  CMAKE_BUILD_PARALLEL_LEVEL : 2
  MAKEFLAGS : " -j 2 "
empregos :
  cancel-runs :
    se : github.event_name == 'pull_request' && github.ref != 'refs/heads/main'
    em execução : ubuntu-latest
    passos :
      - nome : Cancelar execuções anteriores
        usos : styfle/cancel-workflow-action@0.9.1
        com :
          token de acesso : ${{ github.token }}

  trabalho :
    se : ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    nome : ${{ matrix.os }}-${{ matrix.buildtype }}
    execuções em : ${{ matrix.os }}
    estratégia :
      matriz :
        sistema operacional : [windows-2022]
        tipo de construção : [windows-release]
        incluir :
          - sistema operacional : windows-2022
            tripleto : x64-windows-static
            pacotes : >
              cachecol
    passos :
      - nome : Repositório de checkout
        usos : ações/checkout@main

      - nome : CCache
        usos : hendrikmuhs/ccache-action@main
        com :
          tamanho máximo : " 1G "
          variante : " sccache "
          chave : ccache-${{ matrix.os }}-${{ matrix.buildtype }}
          restaurar-chaves : |
            ccache-${{ matrix.os }}
      - nome : Remover MySQL pré-instalado do Windows
        se : contém( matrix.os, 'windows')
        executar : rm -r -fo C:/mysql*

      - nome : Restaurar artefatos e instalar vcpkg
        id : vcpkg-step
        executar : |
          $json=Get-Content vcpkg.json -Raw | ConvertFrom-Json
          $vcpkgCommitId=$json.'builtin-baseline'
          ID de confirmação do vcpkg: $vcpkgCommitId
          eco "VCPKG_GIT_COMMIT_ID=$vcpkgCommitId" | Arquivo de saída -CaminhoDoArquivo $env:GITHUB_ENV -Anexar
      - nome : Obter id de commit vcpkg de vcpkg.json
        usos : lukka/run-vcpkg@main
        com :
          vcpkgGitURL : " https://github.com/microsoft/vcpkg.git "
          vcpkgGitCommitId : ${{ env.VCPKG_GIT_COMMIT_ID }}

      - nome : Obtenha o CMake e o ninja mais recentes
        usos : lukka/get-cmake@main

      - nome : Executar CMake
        usos : lukka/run-cmake@main
        com :
          configurePreset : ${{ matrix.buildtype }}
          buildPreset : ${{ matrix.buildtype }}

      - nome : Criar e carregar artefato
        usos : ações/upload-artefato@principal
        com :
          nome : canário-${{ matrix.buildtype }}-${{ github.sha }}
          caminho : |
            ${{ github.workspace }}/build/${{ matrix.buildtype }}/bin/
